Binary: Don't reset properties when mysql adapter is used
Icinga/ipl-orm pull request #105
Opened 2023-04-12 14:37 UTC by yhabteab

Just use a simple bool flag instead.

2023-04-18 06:38 UTC, nilmerg approved these changes

2023-04-18 21:30 UTC, lippserd requested changes
Let's discuss this PR tomorrow, please.

2023-04-19 08:41 UTC, lippserd requested changes
Please update PR title and description as this change actually allows for subclassing the behavior.

2023-04-19 09:17 UTC, lippserd approved these changes

2023-04-19 15:34 UTC, yhabteab commented
We discussed offline with @nilmerg and agreed not to consider all characters that are not prefixed with `\x` as hex number. The **x509** module already does this correctly by displaying in the search bar (when searching for the subject hash) as hex prefixed with `\x`. So, since **icingadb-web** will need a new release soon, binary data should be displayed there as hex number with `\x` prefixed as well. And thus makes the `rewriteCondition` implementation obsolete and is dropped, which never actually worked properly for what it was intended.

2023-04-19 16:10 UTC, lippserd commented
> agreed not to consider all characters that are not prefixed with `\x` as hex number

This is bytea hex format. `\x$whatever` is valid binary. Only `ctype_xdigit()` is safe. But I don't see why we want to support hex strings for inserts and updates.

> binary data should be displayed ... as hex number with \x

No. Didn't even notice that this is already the case in the certificate monitoring module. If you really want to show that this is a hex string, prefix it with `0x`. Though I strongly suggest not do that. If you cant see that the suggestions are hex strings, `\x` or `0x` won't help you further. Also, this would require to add the prefix for manual values. And we would have to strip them in the behavior and still check whether it's a hex string since the prefix may just be the first characters of a binary string.

> `rewriteCondition` ... which never actually worked properly for what it was intended

Please elaborate. Using hex strings worked perfectly before with the recent fixes I made in this PR. Of course only without the `\x` prefix.

2023-04-19 16:11 UTC, lippserd requested changes
https://github.com/Icinga/ipl-orm/pull/105#issuecomment-1515001270

2023-04-20 08:06 UTC, nilmerg commented
> This is bytea hex format. \x$whatever is valid binary. Only ctype_xdigit() is safe.

*bytea* is a PostgreSQL type, which uses `\xHEX` by chance to represent binary as printable string. If you search for the `\x` prefix, you find nothing which hints at this being used strictly for binary strings, besides PostgreSQL of course.
*ctype_xdigit* is not safe. It only tells you that all characters are hexadecimal. Though, if you ask *ctype_print* it tells you it's ASCII. I know, I know, it's the same, but it shows why *ctype_xdigit* is not **safe**.

We need a prefix. Be it `\x` or `0x`. To being able to independently detect that we have to decode hex in order to get the binary representation.

2023-04-20 08:35 UTC, yhabteab commented
> Please elaborate. Using hex strings worked perfectly before with the recent fixes I made in this PR. Of course only without the `\x` prefix.

Yes, the unit tests did run successfully, but in which use cases would `rewriteCondition` be useful at all? `Binary#toDb()` is always called before `rewriteCondtion()` and thus gets the already transformed data, which results in `ctype_xdigit()` always returning `false`.

2023-04-20 08:58 UTC, lippserd commented
> _bytea_ is a PostgreSQL type, which uses `\xHEX` by chance to represent binary as printable string. If you search for the `\x` prefix, you find nothing which hints at this being used strictly for binary strings, besides PostgreSQL of course.

> Yes, the unit tests did run successfully, but in which use cases would `rewriteCondition` be useful at all? `Binary#toDb()` is always called before `rewriteCondtion()` and thus gets the already transformed(or binary for mysql adapter) data, which results in `ctype_xdigit()` always returning `false`.

My point was that `\x$whatever` is valid binary data where `hex2bin()` must not be called just because it starts with `\x`. The same goes for any other prefix, e.g. `0x`. That's why `toDb()` must not try to do any hex transformation.

Nothing must stop me from inserting hex values like `76616c7565` (`'value'`) or `0x76616c7565`. Now it's true that we would have a problem if we just used `ctype_xdigit()` to do the hex to binary transformation for filters. A prefix makes sense here. Still, we would have to remove the prefix and use `ctype_xidigit()` to check whether the remainders are hex digits. For example, `0xfoobar` is valid binary and not hexadecimal. If I would've inserted `0x76616c7565` my filter must be `0x0x76616c7565` then where no transformation takes place. `ctype_print()` is of no use. You're thinking of binary data being unprintable characters only but that is just not the case.

2023-04-20 10:11 UTC, nilmerg commented
Let's discuss this in person. Should prevent any further misunderstandings.......

2023-04-25 14:54 UTC, lippserd reviewed
Just for the records, do we use a prefix now or not? I have no problem not using a prefix. In the rare case that actual hex values are stored in the database and filters are composed manually, the user has to hex hex 😆. But this is fine for me.

@yhabteab Don't forget to adjust X.509 to not add the `\x` prefix for value suggestions in the search bar.

2023-04-28 09:47 UTC, yhabteab commented
> Just for the records, do we use a prefix now or not?

Only for `PostgreSQL` adapter.

2023-05-15 07:23 UTC, merged