Introduce `BelongsToOne` relation
Icinga/ipl-orm pull request #106
Opened 2023-04-19 10:08 UTC by sukhwinder33445

Required in: https://github.com/Icinga/noma-web/pull/23

2023-04-21 07:05 UTC, nilmerg requested changes

2023-04-21 07:05 UTC, nilmerg commented on src/Relation/BelongsToOne.php
> + * one-to-one relationship with junction table
**a** junction table

2023-04-21 07:05 UTC, nilmerg commented on src/Relations.php
> +     * Define a one-to-one relationship with junction table
**a** junction table

2023-04-21 07:05 UTC, nilmerg commented on src/Relations.php
> +    public function belongsToOne($name, $targetClass)
Add a return type

2023-04-21 09:13 UTC, nilmerg submitted a review, later dismissed

2023-04-25 12:45 UTC, nilmerg approved these changes

2023-04-25 14:43 UTC, lippserd requested changes

2023-04-25 14:43 UTC, lippserd commented on tests/RelationsTest.php
> +        /** @noinspection PhpParamsInspection */
PHPStorm claims that this suppression is redundant. I don't even remember why it's there. Feel free to remove it.

2023-04-27 11:52 UTC, lippserd approved these changes

2023-04-28 06:39 UTC, merged