Raise `BadInputException` in `Behaviors::toDb()` when invalid input i…
Icinga/ipl-orm pull request #88
Opened 2022-11-18 13:40 UTC by yhabteab

…s passed

2022-11-28 09:58 UTC, nilmerg approved these changes

2023-01-17 15:12 UTC, lippserd commented
@nilmerg I don't like `BadInputException` because the name is too general for such a specific use case. Do you perhaps have a suggestion? I like something like `ValueConversionException`.

2023-01-17 15:32 UTC, nilmerg commented
Not really.

2023-01-17 16:28 UTC, lippserd commented on src/Compat/FilterProcessor.php
> +                    $filter->setValue($subjectBehaviors->persistProperty($filter->getValue(), $columnName));
Either the comment should also be moved here or the try-catch block should stay in the same place as the line it replaces. I would prefer the latter.

2023-01-20 07:12 UTC, lippserd requested changes

2023-01-20 07:12 UTC, lippserd commented on src/Compat/FilterProcessor.php
> +                    // The search bar may submit values with wildcards or whatever the user is inputting.
Please write `has entered` instead of `is inputting`.

2023-01-20 08:38 UTC, nilmerg approved these changes

2023-01-27 16:00 UTC, lippserd approved these changes

2023-01-27 16:01 UTC, merged